// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package EntityStruct

import (
	"time"
)

const TableNameFileupload = "fileupload"

// Fileupload mapped from table <fileupload>
type Fileupload struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Filename   string    `gorm:"column:filename" json:"filename"`
	Filepath   string    `gorm:"column:filepath" json:"filepath"`
	Createtime time.Time `gorm:"column:createtime" json:"createtime"`
}

// TableName Fileupload's table name
func (*Fileupload) TableName() string {
	return TableNameFileupload
}
