// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Entity

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"Go_OOP/Technical_Service/Technical_Service/Entity/EntityStruct"
)

func newFileupload(db *gorm.DB, opts ...gen.DOOption) fileupload {
	_fileupload := fileupload{}

	_fileupload.fileuploadDo.UseDB(db, opts...)
	_fileupload.fileuploadDo.UseModel(&EntityStruct.Fileupload{})

	tableName := _fileupload.fileuploadDo.TableName()
	_fileupload.ALL = field.NewAsterisk(tableName)
	_fileupload.ID = field.NewInt64(tableName, "id")
	_fileupload.Filename = field.NewString(tableName, "filename")
	_fileupload.Filepath = field.NewString(tableName, "filepath")
	_fileupload.Createtime = field.NewTime(tableName, "createtime")

	_fileupload.fillFieldMap()

	return _fileupload
}

type fileupload struct {
	fileuploadDo

	ALL        field.Asterisk
	ID         field.Int64
	Filename   field.String
	Filepath   field.String
	Createtime field.Time

	fieldMap map[string]field.Expr
}

func (f fileupload) Table(newTableName string) *fileupload {
	f.fileuploadDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fileupload) As(alias string) *fileupload {
	f.fileuploadDo.DO = *(f.fileuploadDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fileupload) updateTableName(table string) *fileupload {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.Filename = field.NewString(table, "filename")
	f.Filepath = field.NewString(table, "filepath")
	f.Createtime = field.NewTime(table, "createtime")

	f.fillFieldMap()

	return f
}

func (f *fileupload) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fileupload) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 4)
	f.fieldMap["id"] = f.ID
	f.fieldMap["filename"] = f.Filename
	f.fieldMap["filepath"] = f.Filepath
	f.fieldMap["createtime"] = f.Createtime
}

func (f fileupload) clone(db *gorm.DB) fileupload {
	f.fileuploadDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fileupload) replaceDB(db *gorm.DB) fileupload {
	f.fileuploadDo.ReplaceDB(db)
	return f
}

type fileuploadDo struct{ gen.DO }

type IFileuploadDo interface {
	gen.SubQuery
	Debug() IFileuploadDo
	WithContext(ctx context.Context) IFileuploadDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFileuploadDo
	WriteDB() IFileuploadDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFileuploadDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFileuploadDo
	Not(conds ...gen.Condition) IFileuploadDo
	Or(conds ...gen.Condition) IFileuploadDo
	Select(conds ...field.Expr) IFileuploadDo
	Where(conds ...gen.Condition) IFileuploadDo
	Order(conds ...field.Expr) IFileuploadDo
	Distinct(cols ...field.Expr) IFileuploadDo
	Omit(cols ...field.Expr) IFileuploadDo
	Join(table schema.Tabler, on ...field.Expr) IFileuploadDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFileuploadDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFileuploadDo
	Group(cols ...field.Expr) IFileuploadDo
	Having(conds ...gen.Condition) IFileuploadDo
	Limit(limit int) IFileuploadDo
	Offset(offset int) IFileuploadDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFileuploadDo
	Unscoped() IFileuploadDo
	Create(values ...*EntityStruct.Fileupload) error
	CreateInBatches(values []*EntityStruct.Fileupload, batchSize int) error
	Save(values ...*EntityStruct.Fileupload) error
	First() (*EntityStruct.Fileupload, error)
	Take() (*EntityStruct.Fileupload, error)
	Last() (*EntityStruct.Fileupload, error)
	Find() ([]*EntityStruct.Fileupload, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*EntityStruct.Fileupload, err error)
	FindInBatches(result *[]*EntityStruct.Fileupload, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*EntityStruct.Fileupload) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFileuploadDo
	Assign(attrs ...field.AssignExpr) IFileuploadDo
	Joins(fields ...field.RelationField) IFileuploadDo
	Preload(fields ...field.RelationField) IFileuploadDo
	FirstOrInit() (*EntityStruct.Fileupload, error)
	FirstOrCreate() (*EntityStruct.Fileupload, error)
	FindByPage(offset int, limit int) (result []*EntityStruct.Fileupload, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFileuploadDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fileuploadDo) Debug() IFileuploadDo {
	return f.withDO(f.DO.Debug())
}

func (f fileuploadDo) WithContext(ctx context.Context) IFileuploadDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fileuploadDo) ReadDB() IFileuploadDo {
	return f.Clauses(dbresolver.Read)
}

func (f fileuploadDo) WriteDB() IFileuploadDo {
	return f.Clauses(dbresolver.Write)
}

func (f fileuploadDo) Session(config *gorm.Session) IFileuploadDo {
	return f.withDO(f.DO.Session(config))
}

func (f fileuploadDo) Clauses(conds ...clause.Expression) IFileuploadDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fileuploadDo) Returning(value interface{}, columns ...string) IFileuploadDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fileuploadDo) Not(conds ...gen.Condition) IFileuploadDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fileuploadDo) Or(conds ...gen.Condition) IFileuploadDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fileuploadDo) Select(conds ...field.Expr) IFileuploadDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fileuploadDo) Where(conds ...gen.Condition) IFileuploadDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fileuploadDo) Order(conds ...field.Expr) IFileuploadDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fileuploadDo) Distinct(cols ...field.Expr) IFileuploadDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fileuploadDo) Omit(cols ...field.Expr) IFileuploadDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fileuploadDo) Join(table schema.Tabler, on ...field.Expr) IFileuploadDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fileuploadDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFileuploadDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fileuploadDo) RightJoin(table schema.Tabler, on ...field.Expr) IFileuploadDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fileuploadDo) Group(cols ...field.Expr) IFileuploadDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fileuploadDo) Having(conds ...gen.Condition) IFileuploadDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fileuploadDo) Limit(limit int) IFileuploadDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fileuploadDo) Offset(offset int) IFileuploadDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fileuploadDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFileuploadDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fileuploadDo) Unscoped() IFileuploadDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fileuploadDo) Create(values ...*EntityStruct.Fileupload) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fileuploadDo) CreateInBatches(values []*EntityStruct.Fileupload, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fileuploadDo) Save(values ...*EntityStruct.Fileupload) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fileuploadDo) First() (*EntityStruct.Fileupload, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*EntityStruct.Fileupload), nil
	}
}

func (f fileuploadDo) Take() (*EntityStruct.Fileupload, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*EntityStruct.Fileupload), nil
	}
}

func (f fileuploadDo) Last() (*EntityStruct.Fileupload, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*EntityStruct.Fileupload), nil
	}
}

func (f fileuploadDo) Find() ([]*EntityStruct.Fileupload, error) {
	result, err := f.DO.Find()
	return result.([]*EntityStruct.Fileupload), err
}

func (f fileuploadDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*EntityStruct.Fileupload, err error) {
	buf := make([]*EntityStruct.Fileupload, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fileuploadDo) FindInBatches(result *[]*EntityStruct.Fileupload, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fileuploadDo) Attrs(attrs ...field.AssignExpr) IFileuploadDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fileuploadDo) Assign(attrs ...field.AssignExpr) IFileuploadDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fileuploadDo) Joins(fields ...field.RelationField) IFileuploadDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fileuploadDo) Preload(fields ...field.RelationField) IFileuploadDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fileuploadDo) FirstOrInit() (*EntityStruct.Fileupload, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*EntityStruct.Fileupload), nil
	}
}

func (f fileuploadDo) FirstOrCreate() (*EntityStruct.Fileupload, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*EntityStruct.Fileupload), nil
	}
}

func (f fileuploadDo) FindByPage(offset int, limit int) (result []*EntityStruct.Fileupload, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fileuploadDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fileuploadDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fileuploadDo) Delete(models ...*EntityStruct.Fileupload) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fileuploadDo) withDO(do gen.Dao) *fileuploadDo {
	f.DO = *do.(*gen.DO)
	return f
}
